[package]
name = "protoc-rust"
version = "0.1.0"
authors = ["Igor Nikitin <rabbitinspace@icloud.com>"]
edition = "2018"

[[bin]]
name = "protoc-gen-rust"
path = "src/main.rs"

[dependencies]
prost-build = { git = "https://github.com/satelit-project/prost.git", branch = "v0.5.0-protoc" }
tower-grpc-build = { git = "https://github.com/satelit-project/tower-grpc.git", branch = "v0.1.0-protoc" }

[patch.crates-io]
prost-build = { git = "https://github.com/satelit-project/prost.git", branch = "v0.5.0-protoc" }
